name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-mock
        pip install flake8 pytest
        pip install pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pycodestyle to match PEP8 Standards
      continue-on-error: true
      run: |
        pycodestyle src/preprocessing
        pycodestyle src/postprocessing

    - name: Set up environment
      run: |
        mkdir -p $HOME/tmp
        export TMPDIR=$HOME/tmp

    - name: Download test data
      run: |
        wget https://github.com/osoth/testdata/raw/main/subset_cube.fits
        mv subset_cube.fits test_file.fits
        cp test_file.fits data/raw/test_file.fits

    - name: Test with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/src/postprocessing:${{ github.workspace }}/src/preprocessing
      run: |
        pytest
